//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RigaMetro.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_lv_LV {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_lv_LV() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RigaMetro.Resources.SharedResource.lv-LV", typeof(SharedResource_lv_LV).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darbības.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktīvs.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktīvie vilcieni.
        /// </summary>
        internal static string ActiveTrains {
            get {
                return ResourceManager.GetString("ActiveTrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pievienot vilcienu.
        /// </summary>
        internal static string AddTrain {
            get {
                return ResourceManager.GetString("AddTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administratora panelis.
        /// </summary>
        internal static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sākuma laiks ir jābūt agrākam nekā beigu laiks..
        /// </summary>
        internal static string AlertStartTime {
            get {
                return ResourceManager.GetString("AlertStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atcelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pa pulksteņrādītāja virzienu.
        /// </summary>
        internal static string ClockwiseDirection {
            get {
                return ResourceManager.GetString("ClockwiseDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krāsa.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakti.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autortiesības © {0} | Visas tiesības aizsargātas.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pret pulksteņrādītāja virzienu.
        /// </summary>
        internal static string CounterclockwiseDirection {
            get {
                return ResourceManager.GetString("CounterclockwiseDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izveidot.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informācijas panelis.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzēst.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lūdzu, ņemiet vērā.
        /// </summary>
        internal static string DisclaimerNote {
            get {
                return ResourceManager.GetString("DisclaimerNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to šī vietne nav oficiālā Rīgas metro vietne. Visa informācija šajā vietnē ir izdomāta..
        /// </summary>
        internal static string DisclaimerText1 {
            get {
                return ResourceManager.GetString("DisclaimerText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šis projekts izveidots nekomerciāliem izglītojošiem mērķiem..
        /// </summary>
        internal static string DisclaimerText2 {
            get {
                return ResourceManager.GetString("DisclaimerText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rediģēt.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darba beigas.
        /// </summary>
        internal static string EndOfWork {
            get {
                return ResourceManager.GetString("EndOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darba beigas.
        /// </summary>
        internal static string EndWork {
            get {
                return ResourceManager.GetString("EndWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksportēt sarakstu.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metro grafika eksportēšanas cilne tiek izstrādāta..
        /// </summary>
        internal static string ExportDisclaimer {
            get {
                return ResourceManager.GetString("ExportDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neizdevās saglabāt.
        /// </summary>
        internal static string FailedToSave {
            get {
                return ResourceManager.GetString("FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neizdevās atjaunināt līniju.
        /// </summary>
        internal static string FailedToUpdateLine {
            get {
                return ResourceManager.GetString("FailedToUpdateLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neaktīvs.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garums, km.
        /// </summary>
        internal static string LengthKm {
            get {
                return ResourceManager.GetString("LengthKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceļu tīkla garums, km.
        /// </summary>
        internal static string LengthOfNetwork {
            get {
                return ResourceManager.GetString("LengthOfNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Līnija.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Līnijas ID.
        /// </summary>
        internal static string LineID {
            get {
                return ResourceManager.GetString("LineID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Līnijas.
        /// </summary>
        internal static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Līniju saraksts.
        /// </summary>
        internal static string ListOfLines {
            get {
                return ResourceManager.GetString("ListOfLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vilcienu saraksts.
        /// </summary>
        internal static string ListOfTrains {
            get {
                return ResourceManager.GetString("ListOfTrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ienākt.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieslēgšanās kļūda.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iziet.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izveidojis Rostislavs Belovs.
        /// </summary>
        internal static string MadeBy {
            get {
                return ResourceManager.GetString("MadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lai palielinātu karti, izmantojiet Ctrl + peles riteni.
        /// </summary>
        internal static string MapZoomHint {
            get {
                return ResourceManager.GetString("MapZoomHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nosaukums.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jauns vilciens.
        /// </summary>
        internal static string NewTrain {
            get {
                return ResourceManager.GetString("NewTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laika grafiks nav pieejams.
        /// </summary>
        internal static string NoSchedule {
            get {
                return ResourceManager.GetString("NoSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laika grafiks šai stacijai nav pieejams.
        /// </summary>
        internal static string NoScheduleForStation {
            get {
                return ResourceManager.GetString("NoScheduleForStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vilciena numurs.
        /// </summary>
        internal static string NumberOfTrain {
            get {
                return ResourceManager.GetString("NumberOfTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reisu skaits stundā.
        /// </summary>
        internal static string NumberOfTripsPerHour {
            get {
                return ResourceManager.GetString("NumberOfTripsPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atvērt admin paneli.
        /// </summary>
        internal static string OpenAdmin {
            get {
                return ResourceManager.GetString("OpenAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atvērt karti.
        /// </summary>
        internal static string OpenMap {
            get {
                return ResourceManager.GetString("OpenMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parole.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atcerēties mani.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzēst vilcienu?.
        /// </summary>
        internal static string RemoveTrain {
            get {
                return ResourceManager.GetString("RemoveTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rigas Metro | Admina Panelis.
        /// </summary>
        internal static string RigaMetroAdminPanel {
            get {
                return ResourceManager.GetString("RigaMetroAdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saglabāt.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izvēlieties līniju.
        /// </summary>
        internal static string SelectALine {
            get {
                return ResourceManager.GetString("SelectALine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avota kods.
        /// </summary>
        internal static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darba sākums.
        /// </summary>
        internal static string StartOfWork {
            get {
                return ResourceManager.GetString("StartOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darba sākums.
        /// </summary>
        internal static string StartWork {
            get {
                return ResourceManager.GetString("StartWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacijas.
        /// </summary>
        internal static string Stations {
            get {
                return ResourceManager.GetString("Stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika pa līnijām.
        /// </summary>
        internal static string StatisticsByLine {
            get {
                return ResourceManager.GetString("StatisticsByLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statuss.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopsavilkuma statistika.
        /// </summary>
        internal static string SummaryStatistics {
            get {
                return ResourceManager.GetString("SummaryStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tas ir test.
        /// </summary>
        internal static string TestKey {
            get {
                return ResourceManager.GetString("TestKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uz.
        /// </summary>
        internal static string Towards {
            get {
                return ResourceManager.GetString("Towards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vilciena nosaukums.
        /// </summary>
        internal static string TrainName {
            get {
                return ResourceManager.GetString("TrainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vilcieni.
        /// </summary>
        internal static string Trains {
            get {
                return ResourceManager.GetString("Trains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ieplānotie vilcieni.
        /// </summary>
        internal static string TrainsScheduled {
            get {
                return ResourceManager.GetString("TrainsScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reisi dienā.
        /// </summary>
        internal static string TripsPerDay {
            get {
                return ResourceManager.GetString("TripsPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lietotājvārds.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
