//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RigaMetro.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RigaMetro.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active trains.
        /// </summary>
        internal static string ActiveTrains {
            get {
                return ResourceManager.GetString("ActiveTrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Train.
        /// </summary>
        internal static string AddTrain {
            get {
                return ResourceManager.GetString("AddTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Panel.
        /// </summary>
        internal static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start time must be earlier than the end time..
        /// </summary>
        internal static string AlertStartTime {
            get {
                return ResourceManager.GetString("AlertStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clockwise.
        /// </summary>
        internal static string ClockwiseDirection {
            get {
                return ResourceManager.GetString("ClockwiseDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © {0} | All rights reserved.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counterclockwise.
        /// </summary>
        internal static string CounterclockwiseDirection {
            get {
                return ResourceManager.GetString("CounterclockwiseDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note.
        /// </summary>
        internal static string DisclaimerNote {
            get {
                return ResourceManager.GetString("DisclaimerNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this website is not the official website of the Riga Metro. All information on this website is fictional..
        /// </summary>
        internal static string DisclaimerText1 {
            get {
                return ResourceManager.GetString("DisclaimerText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project was created for non-commercial educational purposes..
        /// </summary>
        internal static string DisclaimerText2 {
            get {
                return ResourceManager.GetString("DisclaimerText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of work.
        /// </summary>
        internal static string EndOfWork {
            get {
                return ResourceManager.GetString("EndOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Work.
        /// </summary>
        internal static string EndWork {
            get {
                return ResourceManager.GetString("EndWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Schedule.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tab for exporting the metro schedule is currently under development..
        /// </summary>
        internal static string ExportDisclaimer {
            get {
                return ResourceManager.GetString("ExportDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under development!.
        /// </summary>
        internal static string ExportDisclaimerTitle {
            get {
                return ResourceManager.GetString("ExportDisclaimerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save.
        /// </summary>
        internal static string FailedToSave {
            get {
                return ResourceManager.GetString("FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update line.
        /// </summary>
        internal static string FailedToUpdateLine {
            get {
                return ResourceManager.GetString("FailedToUpdateLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password.
        /// </summary>
        internal static string IncorrectUsernameOrPassword {
            get {
                return ResourceManager.GetString("IncorrectUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length, km.
        /// </summary>
        internal static string LengthKm {
            get {
                return ResourceManager.GetString("LengthKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of road network, km.
        /// </summary>
        internal static string LengthOfNetwork {
            get {
                return ResourceManager.GetString("LengthOfNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line ID.
        /// </summary>
        internal static string LineID {
            get {
                return ResourceManager.GetString("LineID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Lines.
        /// </summary>
        internal static string ListOfLines {
            get {
                return ResourceManager.GetString("ListOfLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of trains.
        /// </summary>
        internal static string ListOfTrains {
            get {
                return ResourceManager.GetString("ListOfTrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by Rostislavs Belovs.
        /// </summary>
        internal static string MadeBy {
            get {
                return ResourceManager.GetString("MadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To zoom the map, use Ctrl + mouse wheel.
        /// </summary>
        internal static string MapZoomHint {
            get {
                return ResourceManager.GetString("MapZoomHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Train.
        /// </summary>
        internal static string NewTrain {
            get {
                return ResourceManager.GetString("NewTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule is missing.
        /// </summary>
        internal static string NoSchedule {
            get {
                return ResourceManager.GetString("NoSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule for this station is missing.
        /// </summary>
        internal static string NoScheduleForStation {
            get {
                return ResourceManager.GetString("NoScheduleForStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of train.
        /// </summary>
        internal static string NumberOfTrain {
            get {
                return ResourceManager.GetString("NumberOfTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of trips per hour.
        /// </summary>
        internal static string NumberOfTripsPerHour {
            get {
                return ResourceManager.GetString("NumberOfTripsPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Admin.
        /// </summary>
        internal static string OpenAdmin {
            get {
                return ResourceManager.GetString("OpenAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Map.
        /// </summary>
        internal static string OpenMap {
            get {
                return ResourceManager.GetString("OpenMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the train?.
        /// </summary>
        internal static string RemoveTrain {
            get {
                return ResourceManager.GetString("RemoveTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riga Metro | Admin Panel.
        /// </summary>
        internal static string RigaMetroAdminPanel {
            get {
                return ResourceManager.GetString("RigaMetroAdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no schedule..
        /// </summary>
        internal static string ScheduleNotFound {
            get {
                return ResourceManager.GetString("ScheduleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a line.
        /// </summary>
        internal static string SelectALine {
            get {
                return ResourceManager.GetString("SelectALine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        internal static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of work.
        /// </summary>
        internal static string StartOfWork {
            get {
                return ResourceManager.GetString("StartOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Work.
        /// </summary>
        internal static string StartWork {
            get {
                return ResourceManager.GetString("StartWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations.
        /// </summary>
        internal static string Stations {
            get {
                return ResourceManager.GetString("Stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics by line.
        /// </summary>
        internal static string StatisticsByLine {
            get {
                return ResourceManager.GetString("StatisticsByLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary statistics.
        /// </summary>
        internal static string SummaryStatistics {
            get {
                return ResourceManager.GetString("SummaryStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is test.
        /// </summary>
        internal static string TestKey {
            get {
                return ResourceManager.GetString("TestKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Towards.
        /// </summary>
        internal static string Towards {
            get {
                return ResourceManager.GetString("Towards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train name.
        /// </summary>
        internal static string TrainName {
            get {
                return ResourceManager.GetString("TrainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trains.
        /// </summary>
        internal static string Trains {
            get {
                return ResourceManager.GetString("Trains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trains scheduled.
        /// </summary>
        internal static string TrainsScheduled {
            get {
                return ResourceManager.GetString("TrainsScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trips per day.
        /// </summary>
        internal static string TripsPerDay {
            get {
                return ResourceManager.GetString("TripsPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
