//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RigaMetro.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RigaMetro.Resources.SharedResource.ru-RU", typeof(SharedResource_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активен.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активные поезда.
        /// </summary>
        internal static string ActiveTrains {
            get {
                return ResourceManager.GetString("ActiveTrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить поезд.
        /// </summary>
        internal static string AddTrain {
            get {
                return ResourceManager.GetString("AddTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Панель администратора.
        /// </summary>
        internal static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальное время должно быть раньше конечного времени..
        /// </summary>
        internal static string AlertStartTime {
            get {
                return ResourceManager.GetString("AlertStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По часовой стрелке.
        /// </summary>
        internal static string ClockwiseDirection {
            get {
                return ResourceManager.GetString("ClockwiseDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © {0} | Все права защищены.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Против часовой стрелки.
        /// </summary>
        internal static string CounterclockwiseDirection {
            get {
                return ResourceManager.GetString("CounterclockwiseDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Панель управления.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратите внимание.
        /// </summary>
        internal static string DisclaimerNote {
            get {
                return ResourceManager.GetString("DisclaimerNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to этот сайт не является официальным сайтом Рижского метро. Вся информация на сайте вымышленная..
        /// </summary>
        internal static string DisclaimerText1 {
            get {
                return ResourceManager.GetString("DisclaimerText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этот проект создан в некоммерческих образовательных целях..
        /// </summary>
        internal static string DisclaimerText2 {
            get {
                return ResourceManager.GetString("DisclaimerText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец работы.
        /// </summary>
        internal static string EndOfWork {
            get {
                return ResourceManager.GetString("EndOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец работы.
        /// </summary>
        internal static string EndWork {
            get {
                return ResourceManager.GetString("EndWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспортировать расписание.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вкладка для экспорта расписания метрополитена находится в процессе разработке..
        /// </summary>
        internal static string ExportDisclaimer {
            get {
                return ResourceManager.GetString("ExportDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при сохранении.
        /// </summary>
        internal static string FailedToSave {
            get {
                return ResourceManager.GetString("FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при обновлении линии.
        /// </summary>
        internal static string FailedToUpdateLine {
            get {
                return ResourceManager.GetString("FailedToUpdateLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неактивен.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина, км.
        /// </summary>
        internal static string LengthKm {
            get {
                return ResourceManager.GetString("LengthKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Протяжённость сети, км.
        /// </summary>
        internal static string LengthOfNetwork {
            get {
                return ResourceManager.GetString("LengthOfNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Линия.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID линии.
        /// </summary>
        internal static string LineID {
            get {
                return ResourceManager.GetString("LineID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Линии.
        /// </summary>
        internal static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список линий.
        /// </summary>
        internal static string ListOfLines {
            get {
                return ResourceManager.GetString("ListOfLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список поездов.
        /// </summary>
        internal static string ListOfTrains {
            get {
                return ResourceManager.GetString("ListOfTrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка входа.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделано Ростиславом Беловым.
        /// </summary>
        internal static string MadeBy {
            get {
                return ResourceManager.GetString("MadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для увеличения карты используйте Ctrl + колесо мыши.
        /// </summary>
        internal static string MapZoomHint {
            get {
                return ResourceManager.GetString("MapZoomHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый поезд.
        /// </summary>
        internal static string NewTrain {
            get {
                return ResourceManager.GetString("NewTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расписание отсутствует.
        /// </summary>
        internal static string NoSchedule {
            get {
                return ResourceManager.GetString("NoSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расписание для данной станции отсутствует.
        /// </summary>
        internal static string NoScheduleForStation {
            get {
                return ResourceManager.GetString("NoScheduleForStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер поезда.
        /// </summary>
        internal static string NumberOfTrain {
            get {
                return ResourceManager.GetString("NumberOfTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество поездок в час.
        /// </summary>
        internal static string NumberOfTripsPerHour {
            get {
                return ResourceManager.GetString("NumberOfTripsPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть админку.
        /// </summary>
        internal static string OpenAdmin {
            get {
                return ResourceManager.GetString("OpenAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть карту.
        /// </summary>
        internal static string OpenMap {
            get {
                return ResourceManager.GetString("OpenMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить поезд?.
        /// </summary>
        internal static string RemoveTrain {
            get {
                return ResourceManager.GetString("RemoveTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рижское метро | Админская панель.
        /// </summary>
        internal static string RigaMetroAdminPanel {
            get {
                return ResourceManager.GetString("RigaMetroAdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите линию.
        /// </summary>
        internal static string SelectALine {
            get {
                return ResourceManager.GetString("SelectALine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исходный код.
        /// </summary>
        internal static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало работы.
        /// </summary>
        internal static string StartOfWork {
            get {
                return ResourceManager.GetString("StartOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало работы.
        /// </summary>
        internal static string StartWork {
            get {
                return ResourceManager.GetString("StartWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Станции.
        /// </summary>
        internal static string Stations {
            get {
                return ResourceManager.GetString("Stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика по линиям.
        /// </summary>
        internal static string StatisticsByLine {
            get {
                return ResourceManager.GetString("StatisticsByLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сводная статистика.
        /// </summary>
        internal static string SummaryStatistics {
            get {
                return ResourceManager.GetString("SummaryStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это тест!.
        /// </summary>
        internal static string TestKey {
            get {
                return ResourceManager.GetString("TestKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В сторону.
        /// </summary>
        internal static string Towards {
            get {
                return ResourceManager.GetString("Towards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название поезда.
        /// </summary>
        internal static string TrainName {
            get {
                return ResourceManager.GetString("TrainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поезда.
        /// </summary>
        internal static string Trains {
            get {
                return ResourceManager.GetString("Trains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запланировано поездов.
        /// </summary>
        internal static string TrainsScheduled {
            get {
                return ResourceManager.GetString("TrainsScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поездок в день.
        /// </summary>
        internal static string TripsPerDay {
            get {
                return ResourceManager.GetString("TripsPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
