// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RigaMetro.Infrastructure.Data;

#nullable disable

namespace RigaMetro.Infrastructure.Migrations
{
    [DbContext(typeof(MetroDbContext))]
    [Migration("20250707173422_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RigaMetro.Web.Models.Line", b =>
                {
                    b.Property<string>("LineID")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndWorkTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsClockwiseDirection")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartWorkTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("LineID");

                    b.ToTable("Lines");

                    b.HasData(
                        new
                        {
                            LineID = "LN01",
                            Color = "#FF0000",
                            EndWorkTime = new DateTime(2000, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            IsClockwiseDirection = true,
                            Name = "Sarkandaugava–Ziepniekkalns",
                            StartWorkTime = new DateTime(2000, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LineID = "LN02",
                            Color = "#00B050",
                            EndWorkTime = new DateTime(2000, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            IsClockwiseDirection = true,
                            Name = "Imanta–Jugla",
                            StartWorkTime = new DateTime(2000, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LineID = "LN03",
                            Color = "#0000FF",
                            EndWorkTime = new DateTime(2000, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            IsClockwiseDirection = true,
                            Name = "Dreilini–Buļļu kāpa",
                            StartWorkTime = new DateTime(2000, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RigaMetro.Web.Models.LineSchedule", b =>
                {
                    b.Property<string>("ScheduleID")
                        .HasColumnType("text");

                    b.Property<bool>("IsClockwise")
                        .HasColumnType("boolean");

                    b.Property<string>("LineID")
                        .IsRequired()
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TripNumber")
                        .HasColumnType("integer");

                    b.HasKey("ScheduleID");

                    b.HasIndex("LineID");

                    b.ToTable("LineSchedules");
                });

            modelBuilder.Entity("RigaMetro.Web.Models.LineStation", b =>
                {
                    b.Property<string>("LineID")
                        .HasColumnType("character varying(8)");

                    b.Property<string>("StationID")
                        .HasColumnType("character varying(8)");

                    b.Property<int>("StationOrder")
                        .HasColumnType("integer");

                    b.HasKey("LineID", "StationID");

                    b.HasIndex("StationID");

                    b.ToTable("LineStations");

                    b.HasData(
                        new
                        {
                            LineID = "LN01",
                            StationID = "ST101",
                            StationOrder = 1
                        },
                        new
                        {
                            LineID = "LN01",
                            StationID = "ST102",
                            StationOrder = 2
                        },
                        new
                        {
                            LineID = "LN01",
                            StationID = "ST103",
                            StationOrder = 3
                        },
                        new
                        {
                            LineID = "LN01",
                            StationID = "ST104",
                            StationOrder = 4
                        },
                        new
                        {
                            LineID = "LN01",
                            StationID = "ST105",
                            StationOrder = 5
                        },
                        new
                        {
                            LineID = "LN01",
                            StationID = "ST106",
                            StationOrder = 6
                        },
                        new
                        {
                            LineID = "LN01",
                            StationID = "ST107",
                            StationOrder = 7
                        },
                        new
                        {
                            LineID = "LN01",
                            StationID = "ST108",
                            StationOrder = 8
                        },
                        new
                        {
                            LineID = "LN01",
                            StationID = "ST109",
                            StationOrder = 9
                        },
                        new
                        {
                            LineID = "LN01",
                            StationID = "ST110",
                            StationOrder = 10
                        },
                        new
                        {
                            LineID = "LN02",
                            StationID = "ST201",
                            StationOrder = 1
                        },
                        new
                        {
                            LineID = "LN02",
                            StationID = "ST202",
                            StationOrder = 2
                        },
                        new
                        {
                            LineID = "LN02",
                            StationID = "ST203",
                            StationOrder = 3
                        },
                        new
                        {
                            LineID = "LN02",
                            StationID = "ST204",
                            StationOrder = 4
                        },
                        new
                        {
                            LineID = "LN02",
                            StationID = "ST205",
                            StationOrder = 5
                        },
                        new
                        {
                            LineID = "LN02",
                            StationID = "ST206",
                            StationOrder = 6
                        },
                        new
                        {
                            LineID = "LN02",
                            StationID = "ST106",
                            StationOrder = 7
                        },
                        new
                        {
                            LineID = "LN02",
                            StationID = "ST208",
                            StationOrder = 8
                        },
                        new
                        {
                            LineID = "LN02",
                            StationID = "ST209",
                            StationOrder = 9
                        },
                        new
                        {
                            LineID = "LN02",
                            StationID = "ST210",
                            StationOrder = 10
                        },
                        new
                        {
                            LineID = "LN02",
                            StationID = "ST211",
                            StationOrder = 11
                        },
                        new
                        {
                            LineID = "LN02",
                            StationID = "ST212",
                            StationOrder = 12
                        },
                        new
                        {
                            LineID = "LN02",
                            StationID = "ST213",
                            StationOrder = 13
                        },
                        new
                        {
                            LineID = "LN02",
                            StationID = "ST214",
                            StationOrder = 14
                        },
                        new
                        {
                            LineID = "LN03",
                            StationID = "ST301",
                            StationOrder = 1
                        },
                        new
                        {
                            LineID = "LN03",
                            StationID = "ST302",
                            StationOrder = 2
                        },
                        new
                        {
                            LineID = "LN03",
                            StationID = "ST303",
                            StationOrder = 3
                        },
                        new
                        {
                            LineID = "LN03",
                            StationID = "ST304",
                            StationOrder = 4
                        },
                        new
                        {
                            LineID = "LN03",
                            StationID = "ST305",
                            StationOrder = 5
                        },
                        new
                        {
                            LineID = "LN03",
                            StationID = "ST208",
                            StationOrder = 6
                        },
                        new
                        {
                            LineID = "LN03",
                            StationID = "ST105",
                            StationOrder = 7
                        },
                        new
                        {
                            LineID = "LN03",
                            StationID = "ST306",
                            StationOrder = 8
                        },
                        new
                        {
                            LineID = "LN03",
                            StationID = "ST307",
                            StationOrder = 9
                        },
                        new
                        {
                            LineID = "LN03",
                            StationID = "ST308",
                            StationOrder = 10
                        },
                        new
                        {
                            LineID = "LN03",
                            StationID = "ST309",
                            StationOrder = 11
                        },
                        new
                        {
                            LineID = "LN03",
                            StationID = "ST310",
                            StationOrder = 12
                        });
                });

            modelBuilder.Entity("RigaMetro.Web.Models.ScheduleStop", b =>
                {
                    b.Property<string>("ScheduleID")
                        .HasColumnType("text");

                    b.Property<int>("StationOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("StationID")
                        .IsRequired()
                        .HasColumnType("character varying(8)");

                    b.HasKey("ScheduleID", "StationOrder");

                    b.HasIndex("StationID");

                    b.ToTable("ScheduleStops");
                });

            modelBuilder.Entity("RigaMetro.Web.Models.Station", b =>
                {
                    b.Property<string>("StationID")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StationID");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            StationID = "ST101",
                            Latitude = 57.003383999999997,
                            Longitude = 24.118736999999999,
                            Name = "Sarkandaugava"
                        },
                        new
                        {
                            StationID = "ST102",
                            Latitude = 56.991002000000002,
                            Longitude = 24.122138,
                            Name = "Rupnica RER"
                        },
                        new
                        {
                            StationID = "ST103",
                            Latitude = 56.974578999999999,
                            Longitude = 24.111671000000001,
                            Name = "Ramulu iela"
                        },
                        new
                        {
                            StationID = "ST104",
                            Latitude = 56.964005999999998,
                            Longitude = 24.106183000000001,
                            Name = "Petersala"
                        },
                        new
                        {
                            StationID = "ST105",
                            Latitude = 56.956935000000001,
                            Longitude = 24.101257,
                            Name = "Kronvalda parks"
                        },
                        new
                        {
                            StationID = "ST106",
                            Latitude = 56.947561,
                            Longitude = 24.119751999999998,
                            Name = "Stacijas laukums"
                        },
                        new
                        {
                            StationID = "ST107",
                            Latitude = 56.933002999999999,
                            Longitude = 24.121713,
                            Name = "Zaķusala"
                        },
                        new
                        {
                            StationID = "ST108",
                            Latitude = 56.919696999999999,
                            Longitude = 24.098175999999999,
                            Name = "Straume"
                        },
                        new
                        {
                            StationID = "ST109",
                            Latitude = 56.912930000000003,
                            Longitude = 24.069526,
                            Name = "Dzintars"
                        },
                        new
                        {
                            StationID = "ST110",
                            Latitude = 56.898448000000002,
                            Longitude = 24.092072999999999,
                            Name = "Ziepniekkalns"
                        },
                        new
                        {
                            StationID = "ST201",
                            Latitude = 56.960270999999999,
                            Longitude = 24.014749999999999,
                            Name = "Imanta"
                        },
                        new
                        {
                            StationID = "ST202",
                            Latitude = 56.945292999999999,
                            Longitude = 24.002022,
                            Name = "Zolitūde"
                        },
                        new
                        {
                            StationID = "ST203",
                            Latitude = 56.930816,
                            Longitude = 24.036110000000001,
                            Name = "Pleskodāle"
                        },
                        new
                        {
                            StationID = "ST204",
                            Latitude = 56.946688999999999,
                            Longitude = 24.048093999999999,
                            Name = "Zasulauks"
                        },
                        new
                        {
                            StationID = "ST205",
                            Latitude = 56.935529000000002,
                            Longitude = 24.072192000000001,
                            Name = "Āgenskalns"
                        },
                        new
                        {
                            StationID = "ST206",
                            Latitude = 56.937130000000003,
                            Longitude = 24.086746999999999,
                            Name = "Uzvaras parks"
                        },
                        new
                        {
                            StationID = "ST208",
                            Latitude = 56.954588000000001,
                            Longitude = 24.118321999999999,
                            Name = "Esplanāde"
                        },
                        new
                        {
                            StationID = "ST209",
                            Latitude = 56.959961999999997,
                            Longitude = 24.130016999999999,
                            Name = "Vidzemes tirgus"
                        },
                        new
                        {
                            StationID = "ST210",
                            Latitude = 56.972436000000002,
                            Longitude = 24.141017999999999,
                            Name = "Brasa"
                        },
                        new
                        {
                            StationID = "ST211",
                            Latitude = 56.973675999999998,
                            Longitude = 24.166967,
                            Name = "VEF"
                        },
                        new
                        {
                            StationID = "ST212",
                            Latitude = 56.983054000000003,
                            Longitude = 24.200993,
                            Name = "Teika"
                        },
                        new
                        {
                            StationID = "ST213",
                            Latitude = 56.987684000000002,
                            Longitude = 24.229665000000001,
                            Name = "Alfa"
                        },
                        new
                        {
                            StationID = "ST214",
                            Latitude = 56.979464,
                            Longitude = 24.253133999999999,
                            Name = "Jugla"
                        },
                        new
                        {
                            StationID = "ST301",
                            Latitude = 56.943384999999999,
                            Longitude = 24.254300000000001,
                            Name = "Dreilini"
                        },
                        new
                        {
                            StationID = "ST302",
                            Latitude = 56.938481000000003,
                            Longitude = 24.210546000000001,
                            Name = "Plavnieki"
                        },
                        new
                        {
                            StationID = "ST303",
                            Latitude = 56.957673999999997,
                            Longitude = 24.184348,
                            Name = "Purvciems"
                        },
                        new
                        {
                            StationID = "ST304",
                            Latitude = 56.953285999999999,
                            Longitude = 24.156230000000001,
                            Name = "Daugavas stadions"
                        },
                        new
                        {
                            StationID = "ST305",
                            Latitude = 56.955894999999998,
                            Longitude = 24.135721,
                            Name = "Matīsa Iela"
                        },
                        new
                        {
                            StationID = "ST306",
                            Latitude = 56.949916000000002,
                            Longitude = 24.087104,
                            Name = "Ķīpsala"
                        },
                        new
                        {
                            StationID = "ST307",
                            Latitude = 56.966904,
                            Longitude = 24.058005999999999,
                            Name = "Iļģuciems"
                        },
                        new
                        {
                            StationID = "ST308",
                            Latitude = 56.975793000000003,
                            Longitude = 24.032716000000001,
                            Name = "Lačupe"
                        },
                        new
                        {
                            StationID = "ST309",
                            Latitude = 56.984631999999998,
                            Longitude = 24.026593999999999,
                            Name = "Kleisti"
                        },
                        new
                        {
                            StationID = "ST310",
                            Latitude = 57.001215999999999,
                            Longitude = 23.987065000000001,
                            Name = "Buļļu kāpa"
                        });
                });

            modelBuilder.Entity("RigaMetro.Web.Models.TimeBetweenStations", b =>
                {
                    b.Property<string>("FromStationID")
                        .HasColumnType("character varying(8)");

                    b.Property<string>("ToStationID")
                        .HasColumnType("character varying(8)");

                    b.Property<int>("DistanceM")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSeconds")
                        .HasColumnType("integer");

                    b.HasKey("FromStationID", "ToStationID");

                    b.HasIndex("ToStationID");

                    b.ToTable("TimeBetweenStations");
                });

            modelBuilder.Entity("RigaMetro.Web.Models.Train", b =>
                {
                    b.Property<string>("TrainID")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EndWorkTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LineID")
                        .IsRequired()
                        .HasColumnType("character varying(8)");

                    b.Property<TimeSpan>("StartWorkTime")
                        .HasColumnType("interval");

                    b.Property<string>("TrainName")
                        .HasColumnType("text");

                    b.HasKey("TrainID");

                    b.HasIndex("LineID");

                    b.ToTable("Trains");

                    b.HasData(
                        new
                        {
                            TrainID = "TR001",
                            EndWorkTime = new TimeSpan(0, 20, 0, 0, 0),
                            IsActive = true,
                            LineID = "LN01",
                            StartWorkTime = new TimeSpan(0, 8, 0, 0, 0),
                            TrainName = "TR–1"
                        },
                        new
                        {
                            TrainID = "TR002",
                            EndWorkTime = new TimeSpan(0, 19, 30, 0, 0),
                            IsActive = true,
                            LineID = "LN01",
                            StartWorkTime = new TimeSpan(0, 7, 30, 0, 0),
                            TrainName = "TR–2"
                        },
                        new
                        {
                            TrainID = "TR201",
                            EndWorkTime = new TimeSpan(0, 21, 0, 0, 0),
                            IsActive = true,
                            LineID = "LN02",
                            StartWorkTime = new TimeSpan(0, 7, 0, 0, 0),
                            TrainName = "TR–Green–1"
                        },
                        new
                        {
                            TrainID = "TR202",
                            EndWorkTime = new TimeSpan(0, 21, 30, 0, 0),
                            IsActive = true,
                            LineID = "LN02",
                            StartWorkTime = new TimeSpan(0, 7, 30, 0, 0),
                            TrainName = "TR–Green–2"
                        },
                        new
                        {
                            TrainID = "TR301",
                            EndWorkTime = new TimeSpan(0, 22, 0, 0, 0),
                            IsActive = true,
                            LineID = "LN03",
                            StartWorkTime = new TimeSpan(0, 6, 0, 0, 0),
                            TrainName = "TR–Blue–1"
                        },
                        new
                        {
                            TrainID = "TR302",
                            EndWorkTime = new TimeSpan(0, 22, 30, 0, 0),
                            IsActive = true,
                            LineID = "LN03",
                            StartWorkTime = new TimeSpan(0, 6, 30, 0, 0),
                            TrainName = "TR–Blue–2"
                        });
                });

            modelBuilder.Entity("RigaMetro.Web.Models.TrainAssignment", b =>
                {
                    b.Property<string>("TrainID")
                        .HasColumnType("text");

                    b.Property<string>("ScheduleID")
                        .HasColumnType("text");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("TrainID", "ScheduleID", "AssignmentDate");

                    b.HasIndex("ScheduleID");

                    b.ToTable("TrainAssignments");
                });

            modelBuilder.Entity("RigaMetro.Web.Models.LineSchedule", b =>
                {
                    b.HasOne("RigaMetro.Web.Models.Line", "Line")
                        .WithMany("LineSchedules")
                        .HasForeignKey("LineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("RigaMetro.Web.Models.LineStation", b =>
                {
                    b.HasOne("RigaMetro.Web.Models.Line", "Line")
                        .WithMany("LineStations")
                        .HasForeignKey("LineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RigaMetro.Web.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("RigaMetro.Web.Models.ScheduleStop", b =>
                {
                    b.HasOne("RigaMetro.Web.Models.LineSchedule", "Schedule")
                        .WithMany("Stops")
                        .HasForeignKey("ScheduleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RigaMetro.Web.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("RigaMetro.Web.Models.TimeBetweenStations", b =>
                {
                    b.HasOne("RigaMetro.Web.Models.Station", "FromStation")
                        .WithMany("TimeFrom")
                        .HasForeignKey("FromStationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RigaMetro.Web.Models.Station", "ToStation")
                        .WithMany("TimeTo")
                        .HasForeignKey("ToStationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStation");

                    b.Navigation("ToStation");
                });

            modelBuilder.Entity("RigaMetro.Web.Models.Train", b =>
                {
                    b.HasOne("RigaMetro.Web.Models.Line", "Line")
                        .WithMany("Trains")
                        .HasForeignKey("LineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("RigaMetro.Web.Models.TrainAssignment", b =>
                {
                    b.HasOne("RigaMetro.Web.Models.LineSchedule", "Schedule")
                        .WithMany("Assignments")
                        .HasForeignKey("ScheduleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RigaMetro.Web.Models.Train", "Train")
                        .WithMany("Assignments")
                        .HasForeignKey("TrainID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("RigaMetro.Web.Models.Line", b =>
                {
                    b.Navigation("LineSchedules");

                    b.Navigation("LineStations");

                    b.Navigation("Trains");
                });

            modelBuilder.Entity("RigaMetro.Web.Models.LineSchedule", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("RigaMetro.Web.Models.Station", b =>
                {
                    b.Navigation("TimeFrom");

                    b.Navigation("TimeTo");
                });

            modelBuilder.Entity("RigaMetro.Web.Models.Train", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
